name: pod_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  logger: ^2.4.0
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.6
  path: ^1.9.0
  sqflite: ^2.3.3+1
  signature: ^5.5.0
  permission_handler: ^11.3.1
  gal: ^2.3.0
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/3.0x/
    - .env
